<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/RailwaySimulator.Application/RailwaySimulator.Application.csproj" />
    <ProjectReference Include="../../src/RailwaySimulator.Cli/RailwaySimulator.Cli.csproj" />
  </ItemGroup>
</Project>
