<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>RailwaySimulator.Cli</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../RailwaySimulator.Application/RailwaySimulator.Application.csproj" />
  </ItemGroup>
</Project>
